### ISSUE TITLE
matron SEGVs when quit

### ISSUE THREAD

**Issue by ngwese** [monome/norns#1426]
I haven't dug in to narrow down the problem but given that SEGV is occurring in a thread which is calling `jack_time_to_frames()` I would assume this is related to the recent changes to the clock subsystem.

cc/ @artfwo 
 
To reproduce run `~/norns/build/matron/matron` and type `q` into the interpreter REPL to quit. Below is the output and the stack trace which gdb shows:

```
...
  PolyPerc
  Icarus
  Thebangs
  Timber
  Passersby
  Rubia
  TestSine
  BandSaw
  None
q
[Thread 0x653fb240 (LWP 4337) exited]
[Thread 0x709fe240 (LWP 4321) exited]
[Thread 0x65bfc240 (LWP 4336) exited]
killing audio engine
[Thread 0x711ff240 (LWP 4320) exited]
stopping OSC server
shutting down lua vm
[Thread 0x68780240 (LWP 4330) exited]
[Thread 0x72dc3240 (LWP 4307) exited]
[Thread 0x713fe240 (LWP 4324) exited]
[Thread 0x71bff240 (LWP 4311) exited]
[Thread 0x725c2240 (LWP 4308) exited]
[Thread 0x735c4240 (LWP 4306) exited]
[Thread 0x73dc5240 (LWP 4305) exited]
[Thread 0x745c6240 (LWP 4304) exited]
[Thread 0x71dc1240 (LWP 4323) exited]
matron shutdown complete
[Thread 0x663fd240 (LWP 4335) exited]
[Thread 0x6b185240 (LWP 4325) exited]
[Thread 0x633f7240 (LWP 4341) exited]
[Thread 0x67f7f240 (LWP 4332) exited]
[Thread 0x66bfe240 (LWP 4334) exited]
[Thread 0x68f81240 (LWP 4329) exited]
[Thread 0x63bf8240 (LWP 4340) exited]
[Thread 0x69782240 (LWP 4328) exited]
[Thread 0x62bf6240 (LWP 4342) exited]
[Thread 0x643f9240 (LWP 4339) exited]
[Thread 0x673ff240 (LWP 4333) exited]
[Thread 0x74a1d240 (LWP 4344) exited]
[Thread 0x75ff9000 (LWP 4297) exited]
[Thread 0x6a984240 (LWP 4326) exited]

Thread 14 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x69f83240 (LWP 4327)]
0x769d21a4 in ?? () from /usr/lib/arm-linux-gnueabihf/libjack.so.0
(gdb) bt
#0  0x769d21a4 in ?? () from /usr/lib/arm-linux-gnueabihf/libjack.so.0
#1  0x769cd1b8 in jack_time_to_frames () from /usr/lib/arm-linux-gnueabihf/libjack.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by artfwo** [comment]
yeah, that's the clock client. perhaps closing jack client in the quit handler can fix this. i didn't know you can quit matron with a user command :)
